// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.TodoListView = (function(_super) {
    __extends(TodoListView, _super);

    function TodoListView() {
      return TodoListView.__super__.constructor.apply(this, arguments);
    }

    TodoListView.prototype.collection = TodoModel;

    TodoListView.prototype.tagName = 'ul';

    TodoListView.prototype.initialize = function() {
      return this.render();
    };

    TodoListView.prototype.render = function() {
      console.log(this.collection);
      _.each(this.collection, function(todoModel) {
        return this.$el.append(new TodoView({
          model: todoModel
        }));
      });
      return $('body').append(this.$el);
    };

    return TodoListView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=TodoListView.map
